### ISSUE TITLE
preview show object at center, but the output object is not at center

### ISSUE THREAD

**Issue by LtotheWT** [googlesamples/android-Camera2Basic#121]
Trying to take picture of an object locate to center of screen, but the picture taken show the object is more to left.
Anyone can help ?

**Comment by GuanacoDevs** [comment]
Any chance you can post screenshots and image?
Your camera layout may help as well.
Regards

**Comment by LtotheWT** [comment]
In AutoFitTextureView class
`@Override`
    `protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {`
        `super.onMeasure(widthMeasureSpec, heightMeasureSpec);`
        `int width = MeasureSpec.getSize(widthMeasureSpec);`
       ` int height = MeasureSpec.getSize(heightMeasureSpec);`
        `if (0 == mRatioWidth || 0 == mRatioHeight) {`
            `setMeasuredDimension(width, height);`
       `} else {`
            `if (width > height * mRatioWidth / mRatioHeight) {`  <b><======= this line</b>
                `setMeasuredDimension(width, width * mRatioHeight / mRatioWidth);`
            `} else {`
                `setMeasuredDimension(height * mRatioWidth / mRatioHeight, height);`
            `}`
        `}`
   ` }`

i know wats the problem that cause the picture not in center. Its because i changed 
 `if (width < height * mRatioWidth / mRatioHeight) {` 
to 
 `if (width > height * mRatioWidth / mRatioHeight) {`.

but if i change change back to  `if (width > height * mRatioWidth / mRatioHeight) {`.
 i would not get a full screen preview. any help ?

**Comment by GuanacoDevs** [comment]
Of you don't get a full screen preview might be because of the ratio chosen for the AutoFitTextureView, if the ratio chosen is 4:3 and your phone has a 16:9 screen, you must get a black area in the Camera preview, if you don't get a Black area, the preview must look stretched(of the ratio chosen was 4:3) one way to see that might be with your native camera application, if you change the ratio you will notice a black area.

**Comment by LtotheWT** [comment]
hi @GuanacoDevs , the ratio chosen is 16:9 in my case. 
this is a sample of the preview.
![screenshot_2018-09-12-13-51-11](https://user-images.githubusercontent.com/13746657/45407355-c371c780-b69b-11e8-8365-d67e0d328948.jpg)

**Comment by GuanacoDevs** [comment]
Can't really tell, but to me it seems like your picture is stretched.
Would you mind posting your layout, if your AutoFitTextureView is set to `match_parent` it will stretch a 4:3 to 16:9
You can check my comment in #113

**Comment by LtotheWT** [comment]
hi @GuanacoDevs 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.example.android.camera2basic.AutoFitTextureView
        android:id="@+id/texture"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true" />

    <FrameLayout
        android:id="@+id/control"
        android:layout_width="match_parent"
        android:layout_height="112dp"
        android:layout_alignParentBottom="true"
        android:layout_alignParentStart="true"
        android:background="@color/control_background">

        <Button
            android:id="@+id/picture"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:text="@string/picture" />

        <ImageButton
            android:id="@+id/info"
            android:contentDescription="@string/description_info"
            style="@android:style/Widget.Material.Light.Button.Borderless"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical|right"
            android:padding="20dp"
            android:src="@drawable/ic_action_info" />

    </FrameLayout>

</RelativeLayout>

above is my xml layout.
And the width and height of setMeasuredDimension() in AutoFitTextureView is 1920 1080, or 1080 1920

**Comment by GuanacoDevs** [comment]
@LtotheWT I don't really use relative layouts but I'd think that maybe, maybe that's why you had the issue in your very first post, because I think that the preview was/is being aligned to the top left of the screen.
I would go
`android:layout_centerHorizontal="true"`
instead of
`android:layout_alignParentStart="true"`
I still believe that from `chooseOptimalSize` you are getting a 4:3 ratio `previewSize`, if that's the case, I'd expect to see a black frame on the bottom, but if you only want to get a 16:9 ratio you'll have to modify `chooseOptimalSize` for that.
Sorry I can't help anymore
Regards

**Comment by LtotheWT** [comment]
thx for help @GuanacoDevs
