### ISSUE TITLE
Camera2 1440x1080 is maximum? What?

### ISSUE THREAD

**Issue by anonym24** [googlesamples/android-Camera2Basic#123]
I'm trying to display normal Full HD preview in landscape orientation (1920x1080) using `Camera2`, but camera returns 1440x1080 as the highest resolution.

With Legacy Camera (`android.hardware.camera`) there was no such issue for the same device. What am I doing wrong?

    CameraManager manager = (CameraManager) getSystemService(Context.CAMERA_SERVICE);
    cameraId = manager.getCameraIdList()[0];
    CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraId);
    StreamConfigurationMap map = characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);
    assert map != null;
    imageDimension = map.getOutputSizes(SurfaceTexture.class)[0];

    for (Size size : map.getOutputSizes(SurfaceTexture.class)) {
        Log.i(TAG, "imageDimension " + size);
    }

Output:

    imageDimension 1440x1080
    imageDimension 1280x960
    imageDimension 1280x720
    imageDimension 864x480
    imageDimension 640x640
    imageDimension 832x486
    imageDimension 800x480
    imageDimension 720x480
    imageDimension 768x432
    imageDimension 640x480

Also it seems that to correctly display preview in landscape we need a lot of headache code like:

    private void configureTransform(int viewWidth, int viewHeight) {
            Activity activity = getActivity();
            if (null == mTextureView || null == mPreviewSize || null == activity) {
                return;
            }
            int rotation = activity.getWindowManager().getDefaultDisplay().getRotation();
            Matrix matrix = new Matrix();
            RectF viewRect = new RectF(0, 0, viewWidth, viewHeight);
            RectF bufferRect = new RectF(0, 0, mPreviewSize.getHeight(), mPreviewSize.getWidth());
            float centerX = viewRect.centerX();
            float centerY = viewRect.centerY();
            if (Surface.ROTATION_90 == rotation || Surface.ROTATION_270 == rotation) {
                bufferRect.offset(centerX - bufferRect.centerX(), centerY - bufferRect.centerY());
                matrix.setRectToRect(viewRect, bufferRect, Matrix.ScaleToFit.FILL);
                float scale = Math.max(
                        (float) viewHeight / mPreviewSize.getHeight(),
                        (float) viewWidth / mPreviewSize.getWidth());
                matrix.postScale(scale, scale, centerX, centerY);
                matrix.postRotate(90 * (rotation - 2), centerX, centerY);
            } else if (Surface.ROTATION_180 == rotation) {
                matrix.postRotate(180, centerX, centerY);
            }
            mTextureView.setTransform(matrix);
        }

From official sample https://github.com/googlesamples/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java#L740

Isn't Camera2 supposed to make things easier than legacy camera? I'm not sure...

Though one good thing I see: we can set many surface targets, with legacy camera we could not use `setPreviewDisplay` and `setPreviewTexture` together, but Camera2 allows many outputs

**Comment by anonym24** [comment]
Next information depressed me:

![image](https://user-images.githubusercontent.com/8851301/45649581-67aca180-bad4-11e8-9940-8bca87e60929.png)


https://stackoverflow.com/questions/31362202/android-camera2-output-sizes#comment50709560_31362202

**Comment by GuanacoDevs** [comment]
@anonym24 I'm not really sure if I can help you, but that's kinda concerning...
For what I understand you want to fill the whole screen with the image without distortion, I think that your best bet at the moment is to come up with a method that will return the biggest output size that is lesser or equals to your device screen; which in this particular case shall be the third option: `imageDimension 1280x720`, currently you are not choosing the best but choosing the first. And obviusly you have to make sure that the `imageReader` is also set to the same 16:9 proportion as the `autoFitTextureView`
Are you using the `chooseOptimalSize()` method?
If you come up with a method that will guarantee that you get `1280x720` your preview might be streched because in your layout you have `match_parent` and it will be stretched to fill the parent, but not distorted and I think that should give you what you want, no?
Perhaps you could try `imageDimension = new Size(1920, 1080);` for testing purposes only, I think it will crash as it is not supported.
Also you might want to check what you get from here to check if you are getting the 16:9 proportion for your imageReader from `map.getOutputSizes(ImageFormat.JPEG)`

Regards

**Comment by GuanacoDevs** [comment]
@anonym24 Would you mind trying my app to see how my camera is displayed on your device, you made me doubt and I have no device like yours to test it, although since I'm using `chooseOptimalSize()` I think it should be ok.
My camera is used to read numbers from a Bingo Card, you don't need to read a Bingo Card only open the camera and check that is ok in your device.
To open the camera in my app:
Menu(top-left)>My Cards>FAB(bottom-right)>Camera(bottom-center)
My app
[UBV](https://play.google.com/store/apps/details?id=com.guanacodevs.ubv)

**Comment by anonym24** [comment]
chooseOptimalSize doesn't make sense here cause it's choose from that list  chooseOptimalSize(map.getOutputSizes(SurfaceTexture.class),

Manually I also tried to set 1920x1080, no crashes, it just stretched 1440 to 1920

**Comment by anonym24** [comment]
using your app it's also not fullscreen (seems also 1080x1440 but portrait orientation):

UBV

![screenshot_2018-09-18-10-37-16-594_com guanacodevs ubv](https://user-images.githubusercontent.com/8851301/45671835-38774e00-bb2f-11e8-9de1-bd60105427db.png)


it should be 1080x1920 (my display size in fullscreen)

**Comment by GuanacoDevs** [comment]
@anonym24 
Thank you for taking the time to test UBV, UBV Camera is OK regarding of what I am expecting, at the end it will crop the top with the guidelines to read the picture, it is located in the internal memory/Android/data/com.guanacodevs.ubv/files

> it should be 1080x1920 (my display size in fullscreen)

I just measured the screenshot and it is in fact 1080x1440, the black frame at the bottom is because I have the `TextureView` to be fixed to the top-center. It chooses 1080x1440 because this is the maximum ratio it gets from `map.getOutputSizes(ImageFormat.JPEG)` when setting the output ratio for the picture to be taken. You can notice a black frame also in your stock camera when you change resolutions.
I suggest to go:
`autoFitTextureView.setAspectRatio(1280, 720)`
and
`texture.setDefaultBufferSize(1280, 720)`
that should show the preview ok(I'm still assuming that you want to show the preview full screen regardless of the resolution not that you want to push the full resolution on the preview)
would you mind sharing your `createCameraPreviewSession` and `setUpCameraOutputs`?

Regards

**Comment by anonym24** [comment]
yes I need normal resolution (fullHd)
because I want to use SurfaceTexture for video recording (MediaCodec + OpenGL)
but Camera2 puts camera frames with 1440x1080 into SurfaceTexture

**Comment by anonym24** [comment]
@GuanacoDevs there is no point to use any calc method as I already tried to manually set 1920x1080 and it didn't work (picture just was stretched from 1440x1080 to 1920x1080)

anyway it doesn't matter anymore as I decided to not use Camera2 api anyway but just stay with legacy api

seems really many phone manufactures just didn't implement it normally

**Comment by anonym24** [comment]
@yudikarma is this a joke? So did you just crop the frame? And how is it related to this issue?

**Comment by anonym24** [comment]
Actually all of this in general is normal thing in Android developing.  https://github.com/googlesamples/android-sunflower/issues/299

**Comment by yudikarma** [comment]
No, before i have isue my preview not full screnn then i chek on here and some one tell to change onmeisure in autofitTextureview.class to make full screen. But that not help, that just scale frame and makes preview full screen and make image capture not same with preview. Then i read this issue and find the problem is camera 2 api output is so small then mw screen. So i need chooseOptimalsize method better to get maximal size output. Then i find and paste that method on that link. So this is not joke

**Comment by anonym24** [comment]
@yudikarma as I said before already I tried to set FullHD (1920x1080) manually and all I got is stretched 1440x1080  to 1920x1080. If got a real 1920x1080 with Camera2 on your devices it doesn't mean that you can get it 100% on other devices

**Comment by alejouribesanchez** [comment]
I was having the same issue and it was affecting my preview image size, I checked step by step and I found there was an issue in the AutoFitTextureView class you should replace

` if (width < height * ratioWidth / ratioHeight)` this by
 if (width > height * ratioWidth / ratioHeight)

after that, the function who gets the largest size will work well.

**Comment by anonym24** [comment]
@alejouribesanchez sorry but you don't understand this issue at all

for just a test you can remove all this calc, auto func, views

get phone with FullHD display resolution (1920x1080)

use ordinary `TextureView`, set its width and height `match_parent`

set width, height to 1920, 1080 (constants) in your code related to camera (`texture.setDefaultBufferSize(1920, 1080)`)

you're the second here trying to suggest no sense (as @yudikarma did)

**Comment by dnhyde** [comment]
I had the same issue... 
Sad news is that there is nothing you can do if the phone manufacturer does not support camera2 (Xiaomi as well in my case). Basically checking with `CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL` in my case it was equal to `CameraMetadata.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY`.
As stated in the [official docs](https://source.android.com/devices/camera/versioning):

> `LEGACY`: These devices expose capabilities to apps through the Camera API2 interfaces that are approximately the same capabilities as those exposed to apps through the Camera API1 interfaces. The legacy frameworks code conceptually translates Camera API2 calls into Camera API1 calls; legacy devices do not support Camera API2 features such as per-frame controls.

But it goes further than that, since apparently the `SCALER_STREAM_CONFIGURATION_MAP` does have access to all possible resolutions that are available through Camera API1, so there must be something wrong in the "conceptual translation" to Camera API1 calls...
This is quite frustrating for developers...

**Comment by Shpingalet007** [comment]
Same thing. Developing app using Honor 8X. As described by anonym24 i have same situation with Camera2 API. I give it Surface object with size that i got as supported from Camera2 - 1920x1080. In fact, when my algorithm selects this size and proceed with it, Camera2 give to my Surface object only 1440x1080 image. It is stretched. I have no idea how to solve it.

Camera2 hardware support level of my device is limited.

**Comment by ancaiova** [comment]
To fix this you must use the correct aspect ratio to compute the optimal preview size. The ratio size is NOT the largest size received from the characteristics (it's most likely to be of different aspect ratio than the phone you're using) used as last parameter in @chooseOptimalSize(choices: Array<Size>,
            textureViewWidth: Int,
            textureViewHeight: Int,
            maxWidth: Int,
            maxHeight: Int,
            aspectRatio: Size).

This last parameter @aspectRatio must be the display's real size ( windowManager.defaultDisplay.getRealSize(outSize: Point!) ) which will give you your screen ratio upon which optimal size is computed.
Hope it helps.

**Comment by anonym24** [comment]
@ancaiova you have no idea what are you talking about

read this https://github.com/googlesamples/android-Camera2Basic/issues/123#issuecomment-457665244

**Comment by ancaiova** [comment]
Well, your question was "what am I doing wrong?" :)
It's quite strange that your device reads as maximum size combination such a small value. I even set may phone to HD resolution and still got SurfaceTex sizes: W 4032 H 3024 as maximum size combination for an Galaxy S7. Have you tried StreamConfigurationMap.isOutputSupportedFor(SurfaceTexture::class.java) 'cause the official documentation says that some of the output classes may not support all formats and sizes combinations and it should be checked with the above mentioned call ... still need to maintain old Camera code until Camera 2 is fully supported.

**Comment by Shpingalet007** [comment]
@anonym24 i solved my problem. After that i moved ISurfaceHolder.SetFixedSize from SurfaceCreated method to OnMeasure everything is okay.

I placed it before View.SetMeasuredDimension.
It helped me, but something in my soul saying me that you tryied it..
Anyway. It looks now like that:
![Снимок экрана 2019-08-09 в 16 42 12](https://user-images.githubusercontent.com/22795961/62787572-44605b80-bac5-11e9-9013-2da44bc29e8f.png)

Hope it helps somebody.

**Comment by anonym24** [comment]
@Shpingalet007 you solved nothing

**Comment by Shpingalet007** [comment]
@anonym24 keep in mind when you creating an issue you are communicating with other. I solved my issue that was the same with described method. If it doesn't works for you - okay. But i tried to help and it worked for me. Good luck

**Comment by anonym24** [comment]
@Shpingalet007 I understand, but you are fourth or fifth user here who absolutely doesn't understand the problem I described in the question. 

You don't need to move any methods if you can set a hardcoded resolution to just test that it doesn't work.

Also there is a method which returns which resolutions supports camera2 on your device:

```
CameraManager manager = (CameraManager) getSystemService(Context.CAMERA_SERVICE);
cameraId = manager.getCameraIdList()[0];
CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraId);
StreamConfigurationMap map = characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);
assert map != null;
imageDimension = map.getOutputSizes(SurfaceTexture.class)[0];

for (Size size : map.getOutputSizes(SurfaceTexture.class)) {
    Log.i(TAG, "imageDimension " + size);
}
```
e.g. Output on some Xiaomi devices:

imageDimension 1440x1080 (the highest... not a full hd)
...
