### ISSUE TITLE
UI thread blocks

### ISSUE THREAD

**Issue by jtfennell** [googlesamples/android-Camera2Basic#41]
The UI blocks when a picture is taken, but with the HandlerThread, it should be performing the write in the background.

**Comment by RoundSparrow** [comment]
At the start of the run() method I added:

            Log.d(TAG, "ImageSaver Runnable on " + Thread.currentThread());

And it seems to NOT be on the Main thread in my testing...

**Comment by mickod** [comment]
As far as I can see it is not actually the UI thread blocking but the Preview focused staying locked. Because the app is mainly showing the preview this makes it appear as if the UI is locked. I've explained the approach I took here - note it is not fully tested for edge conditions and to make sure all the correct tidy up is happening before the unLockFocus but it should give you something to experiment with and build on: http://stackoverflow.com/a/42772736/334402

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
