### ISSUE TITLE
on shaking phone app crashed.

### ISSUE THREAD

**Issue by asbadve** [googlesamples/android-Camera2Basic#65]
If we constantly shake phone internaly images were captures and app crashed.OnPictureTaken() called servral times even if the picture taken called once.

**Comment by rarenivar** [comment]
I was experiencing the same issue on some Android devices, the code for capturing an image was running multiple times, in my case two. It's been almost a year since this issue was open but in case anybody out there is experiencing this bug, the issue seems to be a missing state update when taking a photo. Try [this fix](https://github.com/googlesamples/android-Camera2Basic/pull/94/commits/2c2b1974f37f3560ef71a171de301181e47fd646) by @makowildcat, it worked for me.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
